@Node2_HostAddress = http://localhost:5084

GET {{Node2_HostAddress}}/weatherforecast/
Accept: application/json

###

### Propose from Node2
POST http://localhost:5001/api/paxos/propose
Content-Type: application/json

{
  "FromUserId": 1,
  "ToUserId": 2,
  "Amount": 100
}
